# Configuration File
site_name: "Developer Resources"

nav:
    - Home: index.md
    - Software Development: software_development.md
    - Data Sources: data_cave.md
    - Data Engineering: data_engineering.md
    - Machine Learning: machine_learning.md
    - Azure: azure.md
    - Cheat Sheets: cheat_sheets.md

theme:
  name: material

  font:
    text: DM Sans

  features:
    - header.autohide
  
  palette:
    # Dark Mode  
    - scheme: slate
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
     
    # Light mode
    - scheme: default
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb 
          name: Switch to dark mode
